### ISSUE TITLE
2 issues related to predicting riboSNitches at a variety of temperatures

### ISSUE THREAD

**Issue by MeganSylvia** [The-Bevilacqua-Lab/variantfoldrna#4]
Hi Kobie!

First, I'd just like to say love this tool!

However, I have noticed two small issues related to predicting riboSNitches at a variety of temperatures.

The first is a technical issue: if you are trying to predict riboSNitches at several temperatures simultaneously using the --temperature and --temp-step flags, it does not accept decimal temperature values or temp-step values, however you can run a single temperature prediction at a temperature value with a decimal.

The second issue is something I noticed in the output after predicting RiboSNitches at a variety of temperatures. Over the temperature range I selected (-4C to 38C) a total of 159 SNPs found in the -4C output are absent in the 38C output. I am not sure what is causing this very minimal loss, but I have observed it. Can I share any files with you that would help?

Megan

**Comment by Kobie-Kirven** [comment]
Hi Megan, 

Thank you for using the tool! I have fixed the first issue, I was treating all input temperatures for the temperature range option as integers instead of floats. 

For the second issue, would you mind sending a few of the example SNPs that were in -4 but not in -38? I just need the left flanks, the right flanks, the reference alleles, and the alt alleles. 

Thank you!
Kobie.

**Comment by Kobie-Kirven** [comment]
Hey Megan, 

I think I figured out the issue. There was a rule I had to combine all of the SNPfold chunks together and I had a way of removing blank lines that involved looking for the '-' character since I figured it would be before all of the delta G's. For the SNPs that are missing at the high temperature, they have delta Gs of 0 for both the Ref and the Alt alleles and so they were accidentally removed. I should have fixed it so would you mind re-naming the output folder from your analysis and re-running the pipeline and see if that fixed the issue? (it should just run the combine SNPfold scores steps).  

Best,
Kobie.

**Comment by MeganSylvia** [comment]
Hi Kobie!

Thank you sooo much! I will re-run today and check to see if the issue was
fixed!

Megan

**Comment by MeganSylvia** [comment]
Hi Kobie,

Over the weekend I re-ran vfRNA for my dataset at 10, 15, 20, 25, 30, and 35 *C. From 10 to 35*C I still noticed a very small decrease in the number of SNP positions included by 286. I have attached here the list of entries that are missing in the 35C temp but present in the 10C for both before (OG) and after the update. Hopefully this helps! (Note: One difference between how I ran the script this time and last, is that I ran it on unspliced transcripts). 
[OG_only10_details.txt](https://github.com/user-attachments/files/17366745/OG_only10_details.txt)
[only10_details.txt](https://github.com/user-attachments/files/17366749/only10_details.txt)

Megan

**Comment by Kobie-Kirven** [comment]
Hey Megan, 

The updated code on GitHub should have fixed the issue. Will you try doing a fresh install and rerunning the pipeline to see if you get the same error?

Thanks,
Kobie.

**Comment by MeganSylvia** [comment]
Hi Kobie! 

The fresh install fixed it! I have all the same SNPs at all temperatures in the range now! Thank you!

Megan

**Comment by Kobie-Kirven** [comment]
Hey Megan, That's great to hear! I'll go ahead and close the issue. 

Best,
Kobie.
